/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author DELL
 */
public class FormBangCong extends javax.swing.JPanel {

    /**
     * Creates new form FormBangCong
     */
    public FormBangCong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnBangCong = new javax.swing.JPanel();
        lblMaNhanVien = new javax.swing.JLabel();
        lblChonBangCong = new javax.swing.JLabel();
        cbxBangCong = new javax.swing.JComboBox<>();
        btnThem1 = new com.k33ptoo.components.KButton();
        btnXoa1 = new com.k33ptoo.components.KButton();
        btnSua1 = new com.k33ptoo.components.KButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableBangCong = new javax.swing.JTable();
        cbxMaNhanVien = new javax.swing.JComboBox<>();
        pnChiTietBangCong = new javax.swing.JPanel();
        lblMaBangCong = new javax.swing.JLabel();
        lblSNC = new javax.swing.JLabel();
        lblSNN = new javax.swing.JLabel();
        lblGhiChu = new javax.swing.JLabel();
        txtMaBangCong = new javax.swing.JTextField();
        txtSNC = new javax.swing.JTextField();
        txtSNN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        btnThem = new com.k33ptoo.components.KButton();
        btnXoa = new com.k33ptoo.components.KButton();
        btnSua = new com.k33ptoo.components.KButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableChiTietBangCong = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(800, 600));

        lblMaNhanVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaNhanVien.setText("Mã nhân viên");

        lblChonBangCong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblChonBangCong.setText("Mã bảng công");

        cbxBangCong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxBangCong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThem1.setText("THÊM");
        btnThem1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnXoa1.setText("XÓA");
        btnXoa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnSua1.setText("SỬA");
        btnSua1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tableBangCong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableBangCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Mã bảng công", "Số ngày công", "Số ngày nghỉ", "Ghi chú"
            }
        ));
        jScrollPane3.setViewportView(tableBangCong);

        cbxMaNhanVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxMaNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnBangCongLayout = new javax.swing.GroupLayout(pnBangCong);
        pnBangCong.setLayout(pnBangCongLayout);
        pnBangCongLayout.setHorizontalGroup(
            pnBangCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBangCongLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnBangCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBangCongLayout.createSequentialGroup()
                        .addGroup(pnBangCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaNhanVien)
                            .addComponent(lblChonBangCong))
                        .addGap(37, 37, 37)
                        .addGroup(pnBangCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxBangCong, 0, 120, Short.MAX_VALUE)
                            .addComponent(cbxMaNhanVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnBangCongLayout.createSequentialGroup()
                        .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
            .addComponent(jSeparator2)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnBangCongLayout.setVerticalGroup(
            pnBangCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBangCongLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnBangCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNhanVien)
                    .addComponent(cbxMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnBangCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChonBangCong)
                    .addComponent(cbxBangCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(pnBangCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bảng công", pnBangCong);

        lblMaBangCong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaBangCong.setText("Mã bảng công");

        lblSNC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSNC.setText("Số ngày công");

        lblSNN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSNN.setText("Số ngày nghỉ");

        lblGhiChu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblGhiChu.setText("Ghi chú");

        txtMaBangCong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtSNC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtSNN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtGhiChu.setColumns(20);
        txtGhiChu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtGhiChu.setRows(5);
        jScrollPane1.setViewportView(txtGhiChu);

        btnThem.setText("THÊM");
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnXoa.setText("XÓA");
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnSua.setText("SỬA");
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tableChiTietBangCong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableChiTietBangCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã bảng công", "Số ngày công", "Số ngày nghỉ", "Ghi chú"
            }
        ));
        jScrollPane2.setViewportView(tableChiTietBangCong);

        javax.swing.GroupLayout pnChiTietBangCongLayout = new javax.swing.GroupLayout(pnChiTietBangCong);
        pnChiTietBangCong.setLayout(pnChiTietBangCongLayout);
        pnChiTietBangCongLayout.setHorizontalGroup(
            pnChiTietBangCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pnChiTietBangCongLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnChiTietBangCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChiTietBangCongLayout.createSequentialGroup()
                        .addGroup(pnChiTietBangCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaBangCong)
                            .addComponent(lblSNC)
                            .addComponent(lblSNN))
                        .addGap(61, 61, 61)
                        .addGroup(pnChiTietBangCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaBangCong)
                            .addComponent(txtSNC)
                            .addComponent(txtSNN, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGhiChu)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnChiTietBangCongLayout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnChiTietBangCongLayout.setVerticalGroup(
            pnChiTietBangCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChiTietBangCongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnChiTietBangCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChiTietBangCongLayout.createSequentialGroup()
                        .addGroup(pnChiTietBangCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaBangCong)
                            .addComponent(txtMaBangCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGhiChu))
                        .addGap(24, 24, 24)
                        .addGroup(pnChiTietBangCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSNC)
                            .addComponent(txtSNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnChiTietBangCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSNN)
                    .addComponent(txtSNN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pnChiTietBangCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chi tiết bảng công", pnChiTietBangCong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnSua;
    private com.k33ptoo.components.KButton btnSua1;
    private com.k33ptoo.components.KButton btnThem;
    private com.k33ptoo.components.KButton btnThem1;
    private com.k33ptoo.components.KButton btnXoa;
    private com.k33ptoo.components.KButton btnXoa1;
    private javax.swing.JComboBox<String> cbxBangCong;
    private javax.swing.JComboBox<String> cbxMaNhanVien;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblChonBangCong;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblMaBangCong;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblSNC;
    private javax.swing.JLabel lblSNN;
    private javax.swing.JPanel pnBangCong;
    private javax.swing.JPanel pnChiTietBangCong;
    private javax.swing.JTable tableBangCong;
    private javax.swing.JTable tableChiTietBangCong;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtMaBangCong;
    private javax.swing.JTextField txtSNC;
    private javax.swing.JTextField txtSNN;
    // End of variables declaration//GEN-END:variables
}
