/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author DELL
 */
public class FormKTKL extends javax.swing.JPanel {

    /**
     * Creates new form FormKTKL
     */
    public FormKTKL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnKTKL = new javax.swing.JPanel();
        lblMaNhanVien = new javax.swing.JLabel();
        lblChonKTKL = new javax.swing.JLabel();
        cbxMaNhanVien = new javax.swing.JComboBox<>();
        cbxMaKTKL = new javax.swing.JComboBox<>();
        btnThem1 = new com.k33ptoo.components.KButton();
        btnXoa1 = new com.k33ptoo.components.KButton();
        btnSua1 = new com.k33ptoo.components.KButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableKTKL = new javax.swing.JTable();
        pnChiTietKTKL = new javax.swing.JPanel();
        lblMaKTKL = new javax.swing.JLabel();
        lblLoai = new javax.swing.JLabel();
        lblNgay = new javax.swing.JLabel();
        lblNoiDung = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoiDung = new javax.swing.JTextArea();
        txtKTKL = new javax.swing.JTextField();
        cbxLoai = new javax.swing.JComboBox<>();
        txtNgay = new com.toedter.calendar.JDateChooser();
        btnThem = new com.k33ptoo.components.KButton();
        btnXoa = new com.k33ptoo.components.KButton();
        btnSua = new com.k33ptoo.components.KButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableChiTietKTKL = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(800, 600));

        lblMaNhanVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaNhanVien.setText("Mã nhân viên");

        lblChonKTKL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblChonKTKL.setText("Mã KTKL");

        cbxMaNhanVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxMaNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxMaKTKL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxMaKTKL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThem1.setText("THÊM");
        btnThem1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnXoa1.setText("XÓA");
        btnXoa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnSua1.setText("SỬA");
        btnSua1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tableKTKL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableKTKL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Mã KTKL", "Loại", "Ngày", "Nội dung"
            }
        ));
        jScrollPane3.setViewportView(tableKTKL);

        javax.swing.GroupLayout pnKTKLLayout = new javax.swing.GroupLayout(pnKTKL);
        pnKTKL.setLayout(pnKTKLLayout);
        pnKTKLLayout.setHorizontalGroup(
            pnKTKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKTKLLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnKTKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKTKLLayout.createSequentialGroup()
                        .addGroup(pnKTKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaNhanVien)
                            .addComponent(lblChonKTKL))
                        .addGap(65, 65, 65)
                        .addGroup(pnKTKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxMaKTKL, 0, 120, Short.MAX_VALUE)
                            .addComponent(cbxMaNhanVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnKTKLLayout.createSequentialGroup()
                        .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
            .addComponent(jSeparator2)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnKTKLLayout.setVerticalGroup(
            pnKTKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKTKLLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnKTKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNhanVien)
                    .addComponent(cbxMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnKTKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblChonKTKL)
                    .addComponent(cbxMaKTKL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(pnKTKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Khen thưởng & kỷ luật", pnKTKL);

        lblMaKTKL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaKTKL.setText("Mã KTKL");

        lblLoai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLoai.setText("Loại");

        lblNgay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNgay.setText("Ngày");

        lblNoiDung.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNoiDung.setText("Nội dung");

        txtNoiDung.setColumns(20);
        txtNoiDung.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNoiDung.setRows(5);
        jScrollPane1.setViewportView(txtNoiDung);

        txtKTKL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cbxLoai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThem.setText("THÊM");
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnXoa.setText("XÓA");
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnSua.setText("SỬA");
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tableChiTietKTKL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã KTKL", "Loại", "Ngày", "Nội dung"
            }
        ));
        jScrollPane2.setViewportView(tableChiTietKTKL);

        javax.swing.GroupLayout pnChiTietKTKLLayout = new javax.swing.GroupLayout(pnChiTietKTKL);
        pnChiTietKTKL.setLayout(pnChiTietKTKLLayout);
        pnChiTietKTKLLayout.setHorizontalGroup(
            pnChiTietKTKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChiTietKTKLLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnChiTietKTKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChiTietKTKLLayout.createSequentialGroup()
                        .addGroup(pnChiTietKTKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaKTKL)
                            .addComponent(lblLoai)
                            .addComponent(lblNgay))
                        .addGap(43, 43, 43)
                        .addGroup(pnChiTietKTKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKTKL)
                            .addComponent(cbxLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(172, 172, 172)
                        .addComponent(lblNoiDung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(pnChiTietKTKLLayout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
            .addComponent(jSeparator1)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnChiTietKTKLLayout.setVerticalGroup(
            pnChiTietKTKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChiTietKTKLLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnChiTietKTKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChiTietKTKLLayout.createSequentialGroup()
                        .addGroup(pnChiTietKTKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaKTKL)
                            .addComponent(lblNoiDung)
                            .addComponent(txtKTKL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(pnChiTietKTKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLoai)
                            .addComponent(cbxLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnChiTietKTKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNgay)
                    .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pnChiTietKTKLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chi tiết Khen thưởng & kỷ luật", pnChiTietKTKL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnSua;
    private com.k33ptoo.components.KButton btnSua1;
    private com.k33ptoo.components.KButton btnThem;
    private com.k33ptoo.components.KButton btnThem1;
    private com.k33ptoo.components.KButton btnXoa;
    private com.k33ptoo.components.KButton btnXoa1;
    private javax.swing.JComboBox<String> cbxLoai;
    private javax.swing.JComboBox<String> cbxMaKTKL;
    private javax.swing.JComboBox<String> cbxMaNhanVien;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblChonKTKL;
    private javax.swing.JLabel lblLoai;
    private javax.swing.JLabel lblMaKTKL;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblNoiDung;
    private javax.swing.JPanel pnChiTietKTKL;
    private javax.swing.JPanel pnKTKL;
    private javax.swing.JTable tableChiTietKTKL;
    private javax.swing.JTable tableKTKL;
    private javax.swing.JTextField txtKTKL;
    private com.toedter.calendar.JDateChooser txtNgay;
    private javax.swing.JTextArea txtNoiDung;
    // End of variables declaration//GEN-END:variables
}
