/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author DELL
 */
public class FormLuong extends javax.swing.JPanel {

    /**
     * Creates new form FormLuong
     */
    public FormLuong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnLuong = new javax.swing.JPanel();
        lblMaNhanVien = new javax.swing.JLabel();
        lblChonMaLuong = new javax.swing.JLabel();
        btnThem1 = new com.k33ptoo.components.KButton();
        btnXoa1 = new com.k33ptoo.components.KButton();
        btnSua1 = new com.k33ptoo.components.KButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableLuong = new javax.swing.JTable();
        cbxMaLuong = new javax.swing.JComboBox<>();
        cbxMaNhanVien = new javax.swing.JComboBox<>();
        pnChiTietLuong = new javax.swing.JPanel();
        lblMaLuong = new javax.swing.JLabel();
        lblLuongCoBan = new javax.swing.JLabel();
        lblHSL = new javax.swing.JLabel();
        lblPhuCap = new javax.swing.JLabel();
        lblTienThuong = new javax.swing.JLabel();
        lblTienPhat = new javax.swing.JLabel();
        txtMaLuong = new javax.swing.JTextField();
        txtLuongCoBan = new javax.swing.JTextField();
        txtHSL = new javax.swing.JTextField();
        txtPhuCap = new javax.swing.JTextField();
        txtTienThuong = new javax.swing.JTextField();
        txtTienPhat = new javax.swing.JTextField();
        btnThem = new com.k33ptoo.components.KButton();
        btnXoa = new com.k33ptoo.components.KButton();
        btnSua = new com.k33ptoo.components.KButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableChiTietLuong = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));

        lblMaNhanVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaNhanVien.setText("Mã nhân viên");

        lblChonMaLuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblChonMaLuong.setText("Mã lương");

        btnThem1.setText("THÊM");
        btnThem1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnXoa1.setText("XÓA");
        btnXoa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnSua1.setText("SỬA");
        btnSua1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tableLuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Mã Lương", "Lương cơ bản", "Hệ số lương", "Phụ cấp", "Tiền thưởng", "Tiền phạt"
            }
        ));
        jScrollPane3.setViewportView(tableLuong);

        cbxMaLuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxMaLuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxMaNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnLuongLayout = new javax.swing.GroupLayout(pnLuong);
        pnLuong.setLayout(pnLuongLayout);
        pnLuongLayout.setHorizontalGroup(
            pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLuongLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblChonMaLuong)
                    .addComponent(lblMaNhanVien))
                .addGap(84, 84, 84)
                .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxMaLuong, 0, 120, Short.MAX_VALUE)
                    .addComponent(cbxMaNhanVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator2)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnLuongLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        pnLuongLayout.setVerticalGroup(
            pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLuongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNhanVien)
                    .addComponent(cbxMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChonMaLuong)
                    .addComponent(cbxMaLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lương", pnLuong);

        lblMaLuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaLuong.setText("Mã lương");

        lblLuongCoBan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLuongCoBan.setText("Lương cơ bản");

        lblHSL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblHSL.setText("Hệ số lương");

        lblPhuCap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPhuCap.setText("Phụ cấp");

        lblTienThuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTienThuong.setText("Tiền thưởng");

        lblTienPhat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTienPhat.setText("Tiền phạt");

        txtMaLuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtLuongCoBan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtPhuCap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtTienThuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtTienPhat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnThem.setText("THÊM");
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnXoa.setText("XÓA");
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnSua.setText("SỬA");
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tableChiTietLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã lương", "Lương cơ bản", "Hệ số lương", "Phụ cấp", "Tiền phạt", "Tiền thưởng"
            }
        ));
        jScrollPane1.setViewportView(tableChiTietLuong);

        javax.swing.GroupLayout pnChiTietLuongLayout = new javax.swing.GroupLayout(pnChiTietLuong);
        pnChiTietLuong.setLayout(pnChiTietLuongLayout);
        pnChiTietLuongLayout.setHorizontalGroup(
            pnChiTietLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChiTietLuongLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnChiTietLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChiTietLuongLayout.createSequentialGroup()
                        .addGroup(pnChiTietLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLuongCoBan)
                            .addComponent(lblMaLuong, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHSL, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(28, 28, 28)
                        .addGroup(pnChiTietLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtHSL, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtLuongCoBan)
                            .addComponent(txtMaLuong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnChiTietLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTienThuong, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPhuCap)
                            .addComponent(lblTienPhat))
                        .addGap(43, 43, 43))
                    .addGroup(pnChiTietLuongLayout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)))
                .addGroup(pnChiTietLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChiTietLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTienPhat, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(txtTienThuong)
                        .addComponent(txtPhuCap))
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addComponent(jSeparator1)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnChiTietLuongLayout.setVerticalGroup(
            pnChiTietLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChiTietLuongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnChiTietLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaLuong)
                    .addComponent(lblPhuCap)
                    .addComponent(txtMaLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnChiTietLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLuongCoBan)
                    .addComponent(lblTienThuong)
                    .addComponent(txtLuongCoBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienThuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnChiTietLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHSL)
                    .addComponent(lblTienPhat)
                    .addComponent(txtHSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnChiTietLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnChiTietLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chi tiết Lương", pnChiTietLuong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnSua;
    private com.k33ptoo.components.KButton btnSua1;
    private com.k33ptoo.components.KButton btnThem;
    private com.k33ptoo.components.KButton btnThem1;
    private com.k33ptoo.components.KButton btnXoa;
    private com.k33ptoo.components.KButton btnXoa1;
    private javax.swing.JComboBox<String> cbxMaLuong;
    private javax.swing.JComboBox<String> cbxMaNhanVien;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblChonMaLuong;
    private javax.swing.JLabel lblHSL;
    private javax.swing.JLabel lblLuongCoBan;
    private javax.swing.JLabel lblMaLuong;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblPhuCap;
    private javax.swing.JLabel lblTienPhat;
    private javax.swing.JLabel lblTienThuong;
    private javax.swing.JPanel pnChiTietLuong;
    private javax.swing.JPanel pnLuong;
    private javax.swing.JTable tableChiTietLuong;
    private javax.swing.JTable tableLuong;
    private javax.swing.JTextField txtHSL;
    private javax.swing.JTextField txtLuongCoBan;
    private javax.swing.JTextField txtMaLuong;
    private javax.swing.JTextField txtPhuCap;
    private javax.swing.JTextField txtTienPhat;
    private javax.swing.JTextField txtTienThuong;
    // End of variables declaration//GEN-END:variables
}
