/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author DELL
 */
public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("QUẢN LÝ NHÂN SỰ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        btnTimKiem = new com.k33ptoo.components.KButton();
        btnNhanVien = new com.k33ptoo.components.KButton();
        btnChucVu = new com.k33ptoo.components.KButton();
        btnLuong = new com.k33ptoo.components.KButton();
        btnBangCong = new com.k33ptoo.components.KButton();
        btnKTKL = new com.k33ptoo.components.KButton();
        btnThongKe = new com.k33ptoo.components.KButton();
        pnContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel2.setPreferredSize(new java.awt.Dimension(215, 504));
        kGradientPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 30));

        btnTimKiem.setText("TÌM KIẾM");
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setPreferredSize(new java.awt.Dimension(200, 45));
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTimKiemMousePressed(evt);
            }
        });
        kGradientPanel2.add(btnTimKiem);

        btnNhanVien.setText("NHÂN VIÊN");
        btnNhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNhanVien.setPreferredSize(new java.awt.Dimension(200, 45));
        btnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNhanVienMousePressed(evt);
            }
        });
        kGradientPanel2.add(btnNhanVien);

        btnChucVu.setText("CHỨC VỤ");
        btnChucVu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnChucVu.setPreferredSize(new java.awt.Dimension(200, 45));
        btnChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnChucVuMousePressed(evt);
            }
        });
        kGradientPanel2.add(btnChucVu);

        btnLuong.setText("LƯƠNG");
        btnLuong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuong.setPreferredSize(new java.awt.Dimension(200, 45));
        btnLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLuongMousePressed(evt);
            }
        });
        btnLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuongActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnLuong);

        btnBangCong.setText("BẢNG CÔNG");
        btnBangCong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBangCong.setPreferredSize(new java.awt.Dimension(200, 45));
        btnBangCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBangCongMousePressed(evt);
            }
        });
        btnBangCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBangCongActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnBangCong);

        btnKTKL.setText("KHEN THƯỞNG & KỶ LUẬT");
        btnKTKL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKTKL.setPreferredSize(new java.awt.Dimension(200, 45));
        btnKTKL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKTKLMousePressed(evt);
            }
        });
        kGradientPanel2.add(btnKTKL);

        btnThongKe.setText("THỐNG KÊ");
        btnThongKe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThongKe.setPreferredSize(new java.awt.Dimension(200, 45));
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnThongKeMousePressed(evt);
            }
        });
        kGradientPanel2.add(btnThongKe);

        getContentPane().add(kGradientPanel2, java.awt.BorderLayout.LINE_START);

        pnContainer.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(pnContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMousePressed
        pnContainer.removeAll();
        pnContainer.add(new FormNhanVien());
        pnContainer.repaint();
        pnContainer.revalidate();
        pnContainer.setOpaque(true);
    }//GEN-LAST:event_btnNhanVienMousePressed

    private void btnBangCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBangCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBangCongActionPerformed

    private void btnLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuongActionPerformed

    private void btnChucVuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChucVuMousePressed
        pnContainer.removeAll();
        pnContainer.add(new FormChucVu());
        pnContainer.repaint();
        pnContainer.revalidate();
        pnContainer.setOpaque(true);
    }//GEN-LAST:event_btnChucVuMousePressed

    private void btnLuongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuongMousePressed
        pnContainer.removeAll();
        pnContainer.add(new FormLuong());
        pnContainer.repaint();
        pnContainer.revalidate();
        pnContainer.setOpaque(true);
    }//GEN-LAST:event_btnLuongMousePressed

    private void btnBangCongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBangCongMousePressed
        pnContainer.removeAll();
        pnContainer.add(new FormBangCong());
        pnContainer.repaint();
        pnContainer.revalidate();
        pnContainer.setOpaque(true);
    }//GEN-LAST:event_btnBangCongMousePressed

    private void btnKTKLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKTKLMousePressed
        pnContainer.removeAll();
        pnContainer.add(new FormKTKL());
        pnContainer.repaint();
        pnContainer.revalidate();
        pnContainer.setOpaque(true);
    }//GEN-LAST:event_btnKTKLMousePressed

    private void btnThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMousePressed
        pnContainer.removeAll();
        pnContainer.add(new FormThongKe());
        pnContainer.repaint();
        pnContainer.revalidate();
        pnContainer.setOpaque(true);
    }//GEN-LAST:event_btnThongKeMousePressed

    private void btnTimKiemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMousePressed
        pnContainer.removeAll();
        pnContainer.add(new FormTimKiem());
        pnContainer.repaint();
        pnContainer.revalidate();
        pnContainer.setOpaque(true);
    }//GEN-LAST:event_btnTimKiemMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnBangCong;
    private com.k33ptoo.components.KButton btnChucVu;
    private com.k33ptoo.components.KButton btnKTKL;
    private com.k33ptoo.components.KButton btnLuong;
    private com.k33ptoo.components.KButton btnNhanVien;
    private com.k33ptoo.components.KButton btnThongKe;
    private com.k33ptoo.components.KButton btnTimKiem;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private javax.swing.JPanel pnContainer;
    // End of variables declaration//GEN-END:variables
}
